// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProposalArr = "proposal_arr"

// ProposalArr mapped from table <proposal_arr>
type ProposalArr struct {
	ArrID  int32  `gorm:"column:arr_id;primaryKey;autoIncrement:true" json:"arr_id"`
	Game   string `gorm:"column:game;default:游戏项目" json:"game"`   // 游戏项目
	Nodes  string `gorm:"column:nodes;default:项目环节" json:"nodes"` // 项目环节
	InfoID int32  `gorm:"column:info_id" json:"info_id"`
}

// TableName ProposalArr's table name
func (*ProposalArr) TableName() string {
	return TableNameProposalArr
}
