// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProposalInfo = "proposal_info"

// ProposalInfo mapped from table <proposal_info>
type ProposalInfo struct {
	InfoID         int32     `gorm:"column:info_id;primaryKey;autoIncrement:true" json:"info_id"` // 活动序号
	Place          string    `gorm:"column:place;default:活动位置" json:"place"`                      // 活动位置
	Time           time.Time `gorm:"column:time" json:"time"`                                     // 活动时间
	Department     string    `gorm:"column:department;default:部门名称" json:"department"`            // 部门
	Name           string    `gorm:"column:name;default:活动名称" json:"name"`                        // 活动
	Aim            string    `gorm:"column:aim;default:活动目的" json:"aim"`                          // 活动目的
	Budget         string    `gorm:"column:budget" json:"budget"`                                 // 活动预算
	OptionalTables string    `gorm:"column:optional_tables;default:可选标签" json:"optional_tables"`  // 可选标签
	UID            int32     `gorm:"column:uid" json:"uid"`
}

// TableName ProposalInfo's table name
func (*ProposalInfo) TableName() string {
	return TableNameProposalInfo
}
