// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTag = "tags"

// Tag mapped from table <tags>
type Tag struct {
	Tid         int32  `gorm:"column:tid;primaryKey;autoIncrement:true" json:"tid"`
	Name        string `gorm:"column:name;not null" json:"name"`
	Description string `gorm:"column:description;not null" json:"description"`
}

// TableName Tag's table name
func (*Tag) TableName() string {
	return TableNameTag
}
