// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UID      int32  `gorm:"column:uid;primaryKey;autoIncrement:true" json:"uid"` // 序号
	NickName string `gorm:"column:nick_name;default:昵称" json:"nick_name"`        // 最多七个汉字
	Position string `gorm:"column:position;default:职位" json:"position"`          // 职位
	Tag      string `gorm:"column:tag" json:"tag"`                               // 标签
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
