// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameGame = "game"

// Game mapped from table <game>
type Game struct {
	Gameid   int32  `gorm:"column:gameid;primaryKey;autoIncrement:true" json:"gameid"`
	Gamename string `gorm:"column:gamename;not null" json:"gamename"`
	Venue    string `gorm:"column:venue;not null" json:"venue"`
	Time     string `gorm:"column:time;not null" json:"time"`
	Crowd    string `gorm:"column:crowd;not null" json:"crowd"`
}

// TableName Game's table name
func (Game) TableName() string {
	return TableNameGame
}
