// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameQuestion = "questions"

// Question mapped from table <questions>
type Question struct {
	Qid       int32  `gorm:"column:qid;primaryKey;autoIncrement:true" json:"qid"`
	Questions string `gorm:"column:questions" json:"questions"`
	Type      string `gorm:"column:type" json:"type"`
}

// TableName Question's table name
func (Question) TableName() string {
	return TableNameQuestion
}
