// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameTemplate = "template"

// Template mapped from table <template>
type Template struct {
	Temid   int32  `gorm:"column:temid;primaryKey;autoIncrement:true" json:"temid"`
	Name    string `gorm:"column:name;not null" json:"name"`
	Context string `gorm:"column:context" json:"context"`
}

// TableName Template's table name
func (Template) TableName() string {
	return TableNameTemplate
}
